namespace: 'lordoftheflies'
name: 'ansible_collection_skeleton'
version: '1.0.0'
readme: README.md
authors:
  - lordoftheflies <laszlo.hegedus@cherubits.hu>
description: "Ansible Galaxy collection skeleton."
license:
- Apache-2.0
license_file: 'LICENSE'
tags: ['cherubits', 'skeleton', 'collection']
dependencies: {}
repository: https://github.com/lordoftheflies/ansible_collection_skeleton.git
documentation: https://lordoftheflies.github.io/ansible_collection_skeleton
homepage: https://galaxy.ansible.com/lordoftheflies/ansible_collection_skeleton
issues: https://github.com/lordoftheflies/ansible_collection_skeleton/issues
